CREATE DATABASE employ_PayRoll;
use employ_PayRoll;

CREATE TABLE employ_PayRoll
(ID INT  IDENTITY(1,1) PRIMARY KEY (ID),
NAME VARCHAR(150) ,
SALARY FLOAT,
START DATE );

INSERT INTO employ_PayRoll( NAME, SALARY, START ) VALUES
( 'PRASANNA', 6000000.00, '2022-05-16' ),
( 'JAGADEESH', 7000000.00, '2022-06-17' ),
( 'KUNDANIKA', 400000.00, '2022-07-18' ),
( 'YASHVANTH', 900000.00, '2022-07-15' ),
( 'BHARGAV', 300000.00, '2022-07-15' );


SELECT * FROM employ_PayRoll;

SELECT SALARY FROM employ_PayRoll WHERE NAME = 'PRASANNA';
SELECT * FROM employ_PayRoll WHERE START BETWEEN '2022-06-16' AND CURRENT_TIMESTAMP

ALTER TABLE employ_PayRoll ADD GENDER VARCHAR(10) NULL
UPDATE employ_PayRoll SET GENDER = 'F' WHERE NAME = 'PRASANNA'
UPDATE employ_PayRoll SET GENDER = 'M' WHERE NAME = 'JAGADEESH'
UPDATE employ_PayRoll SET GENDER = 'F' WHERE NAME = 'KUNDANIKA'
UPDATE employ_PayRoll SET GENDER = 'M' WHERE NAME = 'YASHVANTH'
UPDATE employ_PayRoll SET GENDER = 'M' WHERE NAME = 'BHARGAV'




SELECT GENDER, SUM(SALARY) AS SUM_SALARY FROM employ_PayRoll GROUP BY GENDER
SELECT GENDER, MIN(SALARY) AS MIN_SALARY FROM employ_PayRoll GROUP BY GENDER
SELECT GENDER, MAX(SALARY) AS MAX_SALARY FROM employ_PayRoll GROUP BY GENDER
SELECT GENDER, AVG(SALARY) AS AVG_SALARY FROM employ_PayRoll GROUP BY GENDER
SELECT GENDER, COUNT(GENDER) AS EMPLOYEE_COUNT FROM employ_PayRoll GROUP BY GENDER


ALTER TABLE employ_PayRoll ADD PHONENO DECIMAL NOT NULL DEFAULT(0)
UPDATE employ_PayRoll SET PHONENO = 9703088064 WHERE NAME = 'PRASANNA';
UPDATE employ_PayRoll SET PHONENO = 9876543212 WHERE NAME = 'JAGADEESH';
UPDATE employ_PayRoll SET PHONENO = 8765432123 WHERE NAME = 'KUNDANIKA';
UPDATE employ_PayRoll SET PHONENO = 7654321234 WHERE NAME = 'YASHVANTH';
UPDATE employ_PayRoll SET PHONENO = 9123456789 WHERE NAME = 'BHARGAV';
ALTER TABLE employ_PayRoll ADD ADDRESS VARCHAR(100) NOT NULL DEFAULT(''), DEPARTMENT VARCHAR(50) NOT NULL DEFAULT('');
UPDATE employ_PayRoll SET ADDRESS = 'BANGULORE',DEPARTMENT = 'SOFTWARE' WHERE NAME = 'PRASANNA';
UPDATE employ_PayRoll SET ADDRESS = 'KADAPA',DEPARTMENT = 'HARDWARE' WHERE NAME = 'JAGADEESH';
UPDATE employ_PayRoll SET ADDRESS = 'KARNOOL',DEPARTMENT = 'MANAGEMENT' WHERE NAME = 'KUNDANIKA';
UPDATE employ_PayRoll SET ADDRESS = 'CHITWEL',DEPARTMENT = 'PRODUCTION' WHERE NAME = 'YASHVANTH';
UPDATE employ_PayRoll SET ADDRESS = 'CHITTOR',DEPARTMENT = 'AGRICULTURE' WHERE NAME = 'BHARGAV';

ALTER TABLE employ_PayRoll ADD BASIC_PAY FLOAT NOT NULL DEFAULT(0), DEDUCTIONS FLOAT NOT NULL DEFAULT(0),
TAXABLE_PAY FLOAT NOT NULL DEFAULT(0), NET_PAY FLOAT NOT NULL DEFAULT(0)
UPDATE employ_PayRoll SET BASIC_PAY = 90000,DEDUCTIONS = 400,TAXABLE_PAY = 300,NET_PAY = 80300 WHERE ID = 1;
UPDATE employ_PayRoll SET BASIC_PAY = 70000,DEDUCTIONS = 500,TAXABLE_PAY = 300,NET_PAY = 69200 WHERE ID = 2;
UPDATE employ_PayRoll SET BASIC_PAY = 20000,DEDUCTIONS = 300,TAXABLE_PAY = 300,NET_PAY = 19400 WHERE ID = 3;
UPDATE employ_PayRoll SET BASIC_PAY = 30000,DEDUCTIONS = 400,TAXABLE_PAY = 300,NET_PAY = 29300 WHERE ID = 4;
UPDATE employ_PayRoll SET BASIC_PAY = 40000,DEDUCTIONS = 200,TAXABLE_PAY = 300,NET_PAY = 39500 WHERE ID = 5;

INSERT INTO employ_PayRoll VALUES('TERISSA',40000,'2022-07-01','F',9182147305,'KADAPA','Sales&Marketing',40000,300,400,39300)
UPDATE employ_PayRoll SET NAME = 'TERISSA' WHERE ID = 6

SELECT * FROM employ_PayRoll;



