CREATE DATABASE employ_PayRoll;
use employ_PayRoll;
-------uc=2-----------
CREATE TABLE employ_PayRoll
(ID INT  IDENTITY(1,1) PRIMARY KEY (ID),
NAME VARCHAR(150) ,
SALARY FLOAT,
START DATE );
-------uc=3-----------
INSERT INTO employ_PayRoll( NAME, SALARY, START ) VALUES
( 'PRASANNA', 6000000.00, '2022-05-16' ),
( 'JAGADEESH', 7000000.00, '2022-06-17' ),
( 'KUNDANIKA', 400000.00, '2022-07-18' ),
( 'YASHVANTH', 900000.00, '2022-07-15' ),
( 'BHARGAV', 300000.00, '2022-07-15' );

-------uc=4-----------
SELECT * FROM employ_PayRoll;

-------uc=5-----------
SELECT SALARY FROM employ_PayRoll WHERE NAME = 'PRASANNA';
SELECT * FROM employ_PayRoll WHERE START BETWEEN '2022-06-16' AND CURRENT_TIMESTAMP

-------UC=6--------------
ALTER TABLE employ_PayRoll ADD GENDER VARCHAR(10) NULL
UPDATE employ_PayRoll SET GENDER = 'F' WHERE NAME = 'PRASANNA'
UPDATE employ_PayRoll SET GENDER = 'M' WHERE NAME = 'JAGADEESH'
UPDATE employ_PayRoll SET GENDER = 'F' WHERE NAME = 'KUNDANIKA'
UPDATE employ_PayRoll SET GENDER = 'M' WHERE NAME = 'YASHVANTH'
UPDATE employ_PayRoll SET GENDER = 'M' WHERE NAME = 'BHARGAV'

-------UC=7----------
SELECT GENDER, SUM(SALARY) AS SUM_SALARY FROM employ_PayRoll GROUP BY GENDER
SELECT GENDER, MIN(SALARY) AS MIN_SALARY FROM employ_PayRoll GROUP BY GENDER
SELECT GENDER, MAX(SALARY) AS MAX_SALARY FROM employ_PayRoll GROUP BY GENDER
SELECT GENDER, AVG(SALARY) AS AVG_SALARY FROM employ_PayRoll GROUP BY GENDER
SELECT GENDER, COUNT(GENDER) AS EMPLOYEE_COUNT FROM employ_PayRoll GROUP BY GENDER

----------UC=8-------------
ALTER TABLE employ_PayRoll ADD PHONENO DECIMAL NOT NULL DEFAULT(0)
UPDATE employ_PayRoll SET PHONENO = 9703088064 WHERE NAME = 'PRASANNA';
UPDATE employ_PayRoll SET PHONENO = 9876543212 WHERE NAME = 'JAGADEESH';
UPDATE employ_PayRoll SET PHONENO = 8765432123 WHERE NAME = 'KUNDANIKA';
UPDATE employ_PayRoll SET PHONENO = 7654321234 WHERE NAME = 'YASHVANTH';
UPDATE employ_PayRoll SET PHONENO = 9123456789 WHERE NAME = 'BHARGAV';
ALTER TABLE employ_PayRoll ADD ADDRESS VARCHAR(100) NOT NULL DEFAULT(''), DEPARTMENT VARCHAR(50) NOT NULL DEFAULT('');
UPDATE employ_PayRoll SET ADDRESS = 'BANGULORE',DEPARTMENT = 'SOFTWARE' WHERE NAME = 'PRASANNA';
UPDATE employ_PayRoll SET ADDRESS = 'KADAPA',DEPARTMENT = 'HARDWARE' WHERE NAME = 'JAGADEESH';
UPDATE employ_PayRoll SET ADDRESS = 'KARNOOL',DEPARTMENT = 'MANAGEMENT' WHERE NAME = 'KUNDANIKA';
UPDATE employ_PayRoll SET ADDRESS = 'CHITWEL',DEPARTMENT = 'PRODUCTION' WHERE NAME = 'YASHVANTH';
UPDATE employ_PayRoll SET ADDRESS = 'CHITTOR',DEPARTMENT = 'AGRICULTURE' WHERE NAME = 'BHARGAV';

--------------UC=9------------------
ALTER TABLE employ_PayRoll ADD BASIC_PAY FLOAT NOT NULL DEFAULT(0), DEDUCTIONS FLOAT NOT NULL DEFAULT(0),
TAXABLE_PAY FLOAT NOT NULL DEFAULT(0), NET_PAY FLOAT NOT NULL DEFAULT(0)
UPDATE employ_PayRoll SET BASIC_PAY = 90000,DEDUCTIONS = 400,TAXABLE_PAY = 300,NET_PAY = 80300 WHERE ID = 1;
UPDATE employ_PayRoll SET BASIC_PAY = 70000,DEDUCTIONS = 500,TAXABLE_PAY = 300,NET_PAY = 69200 WHERE ID = 2;
UPDATE employ_PayRoll SET BASIC_PAY = 20000,DEDUCTIONS = 300,TAXABLE_PAY = 300,NET_PAY = 19400 WHERE ID = 3;
UPDATE employ_PayRoll SET BASIC_PAY = 30000,DEDUCTIONS = 400,TAXABLE_PAY = 300,NET_PAY = 29300 WHERE ID = 4;
UPDATE employ_PayRoll SET BASIC_PAY = 40000,DEDUCTIONS = 200,TAXABLE_PAY = 300,NET_PAY = 39500 WHERE ID = 5;
---------uc=10------------
INSERT INTO employ_PayRoll VALUES('TERISSA',40000,'2022-07-01','F',9182147305,'KADAPA','Sales&Marketing',40000,300,400,39300)
UPDATE employ_PayRoll SET NAME = 'TERISSA' WHERE ID = 6

-----UC=11--------------
UPDATE employ_PayRoll SET DEPARTMENT = 'Sales' WHERE NAME = 'TERISSA'
INSERT INTO employ_PayRoll VALUES('TERISSA',40000,'2022-07-01','F',9182147305,'KADAPA','MARKETING',40000,300,400,39300)

CREATE TABLE EMPLOYEE
(ID INT IDENTITY(1,1) PRIMARY KEY(ID),
NAME VARCHAR(1),
PHONENO VARCHAR(30),
ADDRESS VARCHAR(250));

SELECT *FROM EMPLOYEE;

CREATE TABLE EmployeeDetails(
ID INT IDENTITY(1,1) PRIMARY KEY(ID),
Emp_Name VARCHAR(1),
Gender VARCHAR(1),
Payroll_ID int not null Foreign key References employ_PayRoll(ID),
ADDRESS VARCHAR(250));
CREATE TABLE Department(Dept_id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,DeptName VARCHAR(50) NOT NULL);

CREATE TABLE Dept_Employee(
Emp_id int NOT NULL Foreign key references EmployeeDetails(ID),
Dept_id int NOT NULL Foreign key references Department(Dept_id) 
);
---------uc=12-------------

SELECT Emp_Name,TAXABLE_PAY from EmployeeDetails,employ_payRoll where EmployeeDetails.Payroll_id=employ_PayRoll.id;


SELECT Emp_Name,TAXABLE_PAY from EmployeeDetails,employ_PayRoll where Start between CAST('2022-06-07' as date) and GETDATE() and  

EmployeeDetails.Payroll_id=employ_PayRoll.id;


SELECT * FROM employ_PayRoll;
